import { Box, Center, Heading, Text, Wrap, WrapItem } from "@chakra-ui/react";
import { Inter } from "@next/font/google";
import Head from "next/head";

import CardSection from "@/components/CardSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pricing UI - Nextjs-ChakraUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w={"100%"} h={"50vh"} bg={"#6B46C1"}>
        <Center>
          <Heading mt={["10", "16"]} color={"white"} pl={["5"]}>
            Simple pricing for your business
          </Heading>
        </Center>
        <Center>
          <Text
            mt={"4"}
            pl={["5"]}
            fontStyle={"normal"}
            fontWeight={"100"}
            color={"#F7FAFC"}
            opacity={"0.9"}
            fontSize={"xl"}
            mb={["8", "12"]}
          >
            Plans that are carefully crafted to suit your business.
          </Text>
        </Center>
        {/* CardSection Component Rendered */}
        <CardSection />
      </Box>
    </>
  );
}
